name: pokemon
channels:
  - conda-forge
  - r
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - ncurses=6.5
  - numpy=2.1.1
  - openssl=3.3.2
  - pandas=2.2.3
  - pip=24.2
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - setuptools=74.1.2
  - six=1.16.0
  - tk=8.6.13
  - tzdata=2024a
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.2.6
  - zstandard=0.23.0
  - zstd=1.5.6
